### ISSUE TITLE
New IP's to add

### ISSUE THREAD

**Issue by PacketOperator** [SilvrrGIT/IP-Lists#1]
Hello - I am new to GitHub when it comes to actual contribution, please forgive me if the preferred procedure is wrong.

I was looking at the IP list, and I think I have a lot of additional stretchoid IPs to contribute.  These are all over my firewall logs, and resolve to various sub-domains of stretchoid.com.

192.241.223.64
192.241.225.76
192.241.213.196
192.241.213.20
192.241.214.228
192.241.225.225
192.241.222.241
192.241.212.150
192.241.212.173
198.199.98.211

**Comment by SilvrrGIT** [comment]
Thanks for providing these, I will look into them and get them added as appropriate!

**Comment by PacketOperator** [comment]
My pleasure - I might have even more.  I manage two firewalls, one for work and one for home - both of my endpoints are being scanned constantly.  Filtering my logs and checking against your list and will probably have some more a little later.

**Comment by PacketOperator** [comment]
I just noticed that this repo is no longer being updated... oops.  Well, I have a lot more to add if you are interested.

zg-0308d-1.stretchoid.com
192.241.223.158

zg-0308a-111.stretchoid.com
192.241.212.247

zg-0308d-110.stretchoid.com
192.241.224.105

zg-0308b-72.stretchoid.com
192.241.214.122

zg-0308a-52.stretchoid.com
192.241.212.118

zg-0308c-138.stretchoid.com
192.241.223.20

zg-0308b-114.stretchoid.com
192.241.215.35

zg-0308e-154.stretchoid.com
192.241.226.44

zg-0308a-23.stretchoid.com
192.241.212.58

zg-0308a-13.stretchoid.com
192.241.201.157

zg-0308b-175.stretchoid.com
192.241.216.55

zg-0308e-141.stretchoid.com
192.241.226.21

zg-0308a-77.stretchoid.com
192.241.212.171

zg-0308a-152.stretchoid.com
192.241.213.85

zg-0308c-75.stretchoid.com
192.241.222.159

zg-0308e-108.stretchoid.com
192.241.225.220

zg-0308d-144.stretchoid.com
192.241.224.163

zg-0308c-126.stretchoid.com
192.241.222.247

zg-0308b-100.stretchoid.com
192.241.214.237

zg-0308c-111.stretchoid.com
192.241.222.222

zg-0308b-53.stretchoid.com
192.241.214.35

zg-0308a-50.stretchoid.com
192.241.212.115

zg-0308c-43.stretchoid.com
192.241.222.112

zg-0308b-5.stretchoid.com
192.241.213.188

zg-0308c-11.stretchoid.com
192.241.219.198

zg-0308d-5.stretchoid.com
192.241.223.165

zg-0308e-74.stretchoid.com
192.241.225.151

zg-0308a-143.stretchoid.com
192.241.213.66

zg-0308b-196.stretchoid.com
192.241.216.109

zg-0308a-194.stretchoid.com
192.241.213.173

zg-0308b-172.stretchoid.com
192.241.216.50

zg-0308b-137.stretchoid.com
192.241.215.228

zg-0308e-129.stretchoid.com
192.241.226.5

zg-0308a-132.stretchoid.com
192.241.213.42

zg-0308d-141.stretchoid.com
192.241.224.160

zg-0308b-113.stretchoid.com
192.241.215.32

zg-0308e-95.stretchoid.com
192.241.225.198

zg-0308e-15.stretchoid.com
192.241.225.62

zg-0308e-118.stretchoid.com
192.241.225.237

zg-0308c-151.stretchoid.com
192.241.223.60

zg-0308c-94.stretchoid.com
192.241.222.180

zg-0308b-112.stretchoid.com
192.241.215.29

zg-0308d-186.stretchoid.com
192.241.225.18

zg-0308b-191.stretchoid.com
192.241.216.96

zg-0308e-183.stretchoid.com
192.241.226.93

zg-0308e-147.stretchoid.com
192.241.226.28

zg-0308b-98.stretchoid.com
192.241.214.230

zg-0308d-59.stretchoid.com
192.241.224.22

zg-0308e-145.stretchoid.com
192.241.226.25

zg-0308a-156.stretchoid.com
192.241.213.91

zg-0308e-38.stretchoid.com
192.241.225.97

zg-0308e-57.stretchoid.com
192.241.225.123

zg-0308a-147.stretchoid.com
192.241.213.77

zg-0308d-40.stretchoid.com
192.241.223.232

zg-0308e-149.stretchoid.com
192.241.226.33

zg-0308e-189.stretchoid.com
192.241.226.105

zg-0308c-102.stretchoid.com
192.241.222.197

zg-0308e-44.stretchoid.com
192.241.225.106

zg-0308a-104.stretchoid.com
192.241.212.228

zg-0308c-118.stretchoid.com
192.241.222.233

zg-0308d-91.stretchoid.com
192.241.224.76

zg-0308a-175.stretchoid.com
192.241.213.127

zg-0308b-129.stretchoid.com
192.241.215.206

zg-0308d-29.stretchoid.com
192.241.223.210

zg-0308e-105.stretchoid.com
192.241.225.216

zg-0308a-29.stretchoid.com
192.241.212.78

zg-0308b-31.stretchoid.com
192.241.213.243

zg-0308c-65.stretchoid.com
192.241.222.147

zg-0308d-49.stretchoid.com
192.241.223.250

zg-0308b-176.stretchoid.com
192.241.216.58

zg-0308a-135.stretchoid.com
192.241.213.51

zg-0308d-151.stretchoid.com
192.241.224.181

zg-0308b-47.stretchoid.com
192.241.214.25

zg-0308b-25.stretchoid.com
192.241.213.231

zg-0308c-77.stretchoid.com
192.241.213.252

zg-0308a-187.stretchoid.com
192.241.213.155

zg-0308b-30.stretchoid.com
192.241.213.240

zg-0308e-50.stretchoid.com
192.241.225.112

**Comment by SilvrrGIT** [comment]
Thanks!  I’m using these lists again so I am maintaining them again. I have 1 or 2 more things to update/verify then I will take that note off.

**Comment by SilvrrGIT** [comment]
All updated, thanks for the help!
