### ISSUE TITLE
New Strtechid IP addres

### ISSUE THREAD

**Issue by pprovart** [SilvrrGIT/IP-Lists#10]
Found this address scanning me 198.199.95.111 if you want to add to your lists.

IP Address: 198.199.95.111
    DNS Hostname (PTR Record): zg-0829h-7.stretchoid.com
    DNS Nameservers: ns3.digitalocean.com, ns1.digitalocean.com, ns2.digitalocean.com
    Network route: 198.199.64.0/18
    Network owner: DigitalOcean LLC
    ASN #: 14061
    Part of range: [198.199.95.0/24](https://ipwhoisinfo.com/range/198.199.95.0/24)

**Comment by SilvrrGIT** [comment]
Added, thanks for contributing.
