### ISSUE TITLE
A couple more for the list

### ISSUE THREAD

**Issue by steveballantyne** [SilvrrGIT/IP-Lists#33]
These have not reached out to me directly, but seem to be Stretchoid owned and are all actively attacking others according to the abuse IP Database ...

192.241.224.9	zg-1220a-69.stretchoid.com	
192.241.224.10	zg-1220a-127.stretchoid.com	
192.241.224.12	zg-1220a-128.stretchoid.com	
192.241.224.14	zg-1220d-102.stretchoid.com	
192.241.224.15	zg-1220d-188.stretchoid.com	
192.241.224.16	zg-1220e-21.stretchoid.com
192.241.224.25	zg-1220h-135.stretchoid.com

**Comment by SilvrrGIT** [comment]
Confirmed as Stretchoid and added to the list.  Thanks!
