### ISSUE TITLE
Add BinaryEdge to your list offering

### ISSUE THREAD

**Issue by jikometrix** [SilvrrGIT/IP-Lists#38]
Hello, 
I created list out of frustration with BinaryEdge.io. They are nice enough keep a list of their own IP's here:

https://api.binaryedge.io/v1/minions

Consider adding them to your list offering. 

Thanks, 
Mike

**Comment by SilvrrGIT** [comment]
Added, https://github.com/SilvrrGIT/IP-Lists/blob/master/binary_edge
