### ISSUE TITLE
google and bing IP bot IP lists

### ISSUE THREAD

**Issue by jikometrix** [SilvrrGIT/IP-Lists#41]
Here are links to google and bing IP bot IP lists. They can be used to prevent blocking google and bing crawlers by accident. 

Or to make sure your site is not crawled by blocking their IPs. Maybe add as plain text ip list like other files. 

https://developers.google.com/search/apis/ipranges/googlebot.json

https://www.bing.com/toolbox/bingbot.json

**Comment by SilvrrGIT** [comment]
Sorry but I am not interested in maintaining additional lists. These started based on personal use and what I needed to reduce some noise in my logs.  I encourage you to start a repository with theses lists if you find them useful.
