### ISSUE TITLE
Instructions for FreshTomato

### ISSUE THREAD

**Issue by AnderssonPeter** [SilvrrGIT/IP-Lists#54]
Hi I just created a github page that has instruction's on how to use your list for FreshTomato, would a pull request that adds a link to it be accepted? (You are mentioned under [Acknowledgements](https://anderssonpeter.github.io/tomato-block-malicious-ips/#acknowledgements))

**Comment by SilvrrGIT** [comment]
No, thanks.  Id like to keep this Repo limited to a few simple lists that I and those that contribute find useful.  The more that gets added the more there is to keep updated.
