### ISSUE TITLE
amazon_ec2_us List

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/IP-Lists#67]
I am no longer using the [amazon_ec2_us](https://github.com/SilvrrGIT/IP-Lists/blob/master/amazon_ec2_us) list and haven't been maintaining it.  I am also not seeing any issues or pull requests for updates.

I plan to remove the [amazon_ec2_us](https://github.com/SilvrrGIT/IP-Lists/blob/master/amazon_ec2_us) list at the end of April 2023 unless I hear that it is still needed.

**Comment by SilvrrGIT** [comment]
This list has been removed.  Anyone utilizing the list is welcome to re-instate it and provide maintenance for it moving forward.

**Comment by szepeviktor** [comment]
Tips for googlers.

1. You can get an always fresh list of AWS IP addresses: `https://ip-ranges.amazonaws.com/ip-ranges.json`
2. And tailor to your needs, e.g. Cloudfront IP-s `jq -r '(.prefixes[] | select(.service == "CLOUDFRONT").ip_prefix),(.ipv6_prefixes[] | select(.service == "CLOUDFRONT").ipv6_prefix)'`
