### ISSUE TITLE
New shodan.io and internettl.org IPs

### ISSUE THREAD

**Issue by r-sherwood** [SilvrrGIT/IP-Lists#72]
165.227.62.247     
247.62.227.165.in-addr.arpa domain name pointer mango.census.shodan.io.

104.152.52.219
219.52.152.104.in-addr.arpa domain name pointer internettl.org.

104.152.52.236
236.52.152.104.in-addr.arpa domain name pointer internettl.org.

--------------
Guess the whole 104.152.52.0/24 subnet will be used in the future
 
104.152.52.1
1.52.152.104.in-addr.arpa domain name pointer internettl.org.
104.152.52.254
254.52.152.104.in-addr.arpa domain name pointer internettl.org.

**Comment by szepeviktor** [comment]
I use a script that scans know host names.
https://github.com/szepeviktor/debian-server-tools/blob/ce64fbc2e0f3672392ec51e1536198a852d8de56/security/myattackers-ipsets/ipset/shodan.ipset#L14-L18

**Comment by r-sherwood** [comment]
Thx for the script, but it fails if new subdomains are used. The new "mango.census.shodan.io" will not be queried.

**Comment by SilvrrGIT** [comment]
Added in:
https://github.com/SilvrrGIT/IP-Lists/commit/50d1edd499f3d5e73d6f775404553d9943412ad5
and 
https://github.com/SilvrrGIT/IP-Lists/commit/16923793ab2507e6f871affb7c7176902c31646d

**Comment by r-sherwood** [comment]
@szepeviktor FYI: I've created a subdomain enumeration for shodan.io with OWASP-amass tool, you can find the result [here](https://github.com/r-sherwood/IP-Lists/blob/main/amass_all_shodan_domains.txt).

**Comment by szepeviktor** [comment]
@r-sherwood Thank you for sharing that with me.

Please be aware that many of those are Cloudflare IP addresses.
