### ISSUE TITLE
.py for looping over IPs with Linux ufw

### ISSUE THREAD

**Issue by mrosas47** [SilvrrGIT/IP-Lists#83]
Hello! I absolutely loved this list, I was so sick of stretchoid. I use Ubuntu 22.04.2 LTS, and I wanted to deny all of these IPs with ufw (uncomplicated firewall), so I wrote a .py script that loops over every line of a blacklist.txt copied from your list and runs `sudo ufw deny from {ip} to any`. I'll share both files (both as txt because github won't allow .py), I hope you find it useful!

[blacklist.txt](https://github.com/SilvrrGIT/IP-Lists/files/11751865/blacklist.txt) 
[blacklist-py.txt](https://github.com/SilvrrGIT/IP-Lists/files/11751884/blacklist-py.txt)

**Comment by szepeviktor** [comment]
```bash
sed -e 's#\s##g; /^$/d' /mnt/archive/blacklist.txt | xargs -I% -- sudo ufw deny from % to any
```

**Comment by SilvrrGIT** [comment]
Thanks for the info!
